// export const NodeJSURL = 'ws://localhost:8081';
export const NodeJSURL = 'wss://bbdipl.herokuapp.com';
export const baseURL = 'http://localhost:8080';
// export const baseURL = 'https://sportsgeekapi.herokuapp.com';
// export const baseURL = 'https://sportsgeek-api-qa.herokuapp.com' //qa
export const usersBaseURL = baseURL +'/users';
export const authBaseURL = baseURL +'/users/authenticate';
export const matchBaseURL = baseURL + '/matches';
export const contestBaseURL = baseURL + '/contest';
export const rechargeBaseURL = baseURL + '/recharge';
export const teamBaseURL = baseURL + '/teams';
export const venueBaseURL = baseURL + '/venues';
export const tournamentBaseURL = baseURL + '/tournaments';
export const chatBaseURL = baseURL + '/public-chat';
export const ContestLogBaseURL = baseURL + '/contest-log';
